### ISSUE TITLE
Image didn't show correctly.

### ISSUE THREAD

**Issue by Explorare** [arianrhodsandlot/Holly-Quintet#5]
![](https://c.hime.io/images/drGw.png)

**Comment by arianrhodsandlot** [comment]
试一下“不使用缓存重新搜索”呢？如果还是不行可以把关键词反馈一下。

**Comment by Explorare** [comment]
不使用缓存重新搜索” 无效
关键词「ご注文はうさぎですか?? ORIGINAL SOUNDTRACK」

**Comment by arianrhodsandlot** [comment]
确实是由于没有处理好搜索词里的特殊字。在修好这个问题之前暂时去掉问号搜“[ご注文はうさぎですか ORIGINAL SOUNDTRACK](http://hollyquintet.tomaketheendofbattle.com/covers?query=%E3%81%94%E6%B3%A8%E6%96%87%E3%81%AF%E3%81%86%E3%81%95%E3%81%8E%E3%81%A7%E3%81%99%E3%81%8B%20ORIGINAL%20SOUNDTRACK&scope=amazon-jp)”凑合用吧。

**Comment by Explorare** [comment]
好的，感谢
