### ISSUE TITLE
一个小建议(Advice of Enhancement)

### ISSUE THREAD

**Issue by Rirmach** [arianrhodsandlot/Holly-Quintet#7]
由于音乐整理一般都会同时使用一些相关软件，例如foobar2000或者MP3tag之类。能否开发一个针对fb2k或者MP3tag的插件以集成该功能，实现一键搜索和添加封面。

**Comment by arianrhodsandlot** [comment]
很遗憾，一方面我对这部分软件技术并不熟悉，另一方面将功能放在网站就是为了让任何播放器用户——iTunes、foobar2000甚至Amarok用户都能使用。
但通过把文件拖到网页中来更新ID3里的图片在技术上或许是可行的，有时间我调研一番。
